# Site settings
title: "Vitaliy Ryepnoy"
email: vitdotonline@gmail.com
description: "A technology blog by Vitaliy Ryepnoy."
baseurl: ""
url: "https://vitr.github.io/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "http://2.gravatar.com/avatar/63e9889131930cf2e2e97eb559f443c5?s=200"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
#github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-575be88ca22466d5
post_limit: 5

# Social usernames/URLs
twitter_username: vitdotonline
github_username:  vitr
linkedin_link: https://au.linkedin.com/in/vitaliyr
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: https://stackoverflow.com/users/4986182/vitr

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> using <a href=\"http://jekyllrb.com/\">Jekyll</a>"
footer_right: "theme <a href='http://jekyllthemes.org/themes/carte-noire/' target='_blank'>Carte Noire</a>"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
